        What is the difference between __getattr__ and __getattribute__ - when are they called ?
    
    What are the conditions under which the the right hand operator family of magic 
    method are called (for instance __radd__, __rmul__)
    
    Under what conditions should you make a class hashable
    
    Explain the difference between a Iterator and Iterable
    
    What is needed to make a class iterable
    
    What is required to make a class a context manager.

        How do you call a C function using the Python standard library?[1]
    
    What is an appropriate usecase for the __new__ method?[2]
    
    What type is used to represent all Python objects in the CPython C API?[3]

    How would you lazily iterate over the members of a binary tree?[4]
    
    What keyword could be used to reduce the length of the above btree iterator by two lines?[5]
    
    What is the relationship between coroutines and generator functions in Python? 
    
    How might you use one to implement the other?[6][7]

    
    How many bytecode instructions are used to execute this code? myfunc(a, b)[8]

    Which two standard library modules provide task distribution pools? [9] [10] (yes, there is a third, but it’s a secret)

    What is the function of the __slots__ class variable?[11]
    
    When using __slots__, class instances can no longer be pickled. How can this ability be restored?

Que-->Can you write code to determine the name of an object in Python?
------------

    Ans. No objects in Python have any associated names. So there is no way of getting the one for an object. The assignment is only the means of binding a name to the value. The name then can only refer to access the value. The most we can do is to find the reference name of the object.



    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    The get() method returns the value for the specified key if the key is in the dictionary.

In [1]:
marks = {'math':66,'Physics':76}

marks.get('math')

66

    get() Parameters
    
    get() method takes maximum of two parameters:

    key - key to be searched in the dictionary

    value (optional) - Value to be returned if the key is not found. The default value is None.

In [2]:
marks.get('math',88)

66

In [5]:
marks.get('mathemtic')

In [6]:
marks.get("mathematics",1002)

1002

In [7]:
marks

{'math': 66, 'Physics': 76}

matrix 
-----

In [19]:
import numpy as np

A = np.arange(1,7)
print(f"A  =  {A}")

print(A.ndim)

B = A.reshape(2,3)
print(f"{B} ")

print('____________np.reshape()______________')
C = A.reshape(3,2)
print(C)


print('____________np.reshape()______________')
D = A.reshape(len(A),1)
print(D)

print('____________np.reshape()______________')
D = A.reshape(6,1)
print(D)




A  =  [1 2 3 4 5 6]
1
[[1 2 3]
 [4 5 6]] 
____________np.reshape()______________
[[1 2]
 [3 4]
 [5 6]]
____________np.reshape()______________
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
____________np.reshape()______________
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


# Addition of Two Matrices



In [22]:
F = np.array([[12,19],[-46,23]])

G = np.array([[15,-30],[33,-17]])

F + G

array([[ 27, -11],
       [-13,   6]])

# matrix Multiplication

In [23]:
F.dot(G)

array([[ 807, -683],
       [  69,  989]])

# Transpose

In [25]:
F

array([[ 12,  19],
       [-46,  23]])

In [24]:
F.transpose()

array([[ 12, -46],
       [ 19,  23]])

In [31]:
I = np.arange(12,24)
I

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [37]:
S = I.reshape(4,3)
S

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [38]:
S.transpose()

array([[12, 15, 18, 21],
       [13, 16, 19, 22],
       [14, 17, 20, 23]])

# Access rows of a Matrix

In [43]:
print(S[0])
print('S first col first element : ',S[0][0])
print('S first element : ',S[0][2])

[12 13 14]
S first col first element :  12
S first element :  14


In [53]:
S[::]

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

    [ row:end_rows,  col : end_col ]

In [55]:
S[:,2]

array([14, 17, 20, 23])

In [59]:
S[0:2,:]

array([[12, 13, 14],
       [15, 16, 17]])

    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In [60]:
R = int(input("Enter The Number of Rows"))

C = int(input("Enter The Number Of Column"))

matrix = []

for i in range(R):
    a = []

    for j in range(C):
        a.append(int(input()))

    matrix.append(a)

# for printing The Matrix

for i in range(R):
    for j in range(C):
        print(matrix[i][j], end=" ")
    print()

1 2 3 
4 5 6 


In [63]:
matrix

[[1, 2, 3], [4, 5, 6]]

In [66]:
import numpy as np
matrix2 = [[12,14,16],[22,24,26]]

matrix3 = np.array(matrix2).reshape(3,2)
matrix3

array([[12, 14],
       [16, 22],
       [24, 26]])